/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-11-01 01:23:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_005fworking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>PotoPotoPhoto+</title>\n");
      out.write("<link rel = \"stylesheet\" href = \"/stylesheets/potopotophoto.css\" type = \"text/css\" />\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\tvar loginFeature = {\n");
      out.write("\t\tloginStatus : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login_Status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\n");
      out.write("\t\tuserNickName : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\n");
      out.write("\t\tloginErrorMessage : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\n");
      out.write("\t\tlogin_Status_On : \"1\",\n");
      out.write("\t\tlogin_Status_Off : \"0\",\n");
      out.write("\t\t\n");
      out.write("\t\tloginStatusDisplay : function() {\n");
      out.write("\t\t\tif (this.loginStatus === this.login_Status_On)\n");
      out.write("\t\t\t\tdocument.getElementById(\"loginStatus\").innerHTML = this.userNickName + \" 님, 반갑습니다!\";\n");
      out.write("\t\t\telse\n");
      out.write("\t\t\t\tdocument.getElementById(\"loginStatus\").innerHTML = \"로그인 되지 않았습니다.\";\n");
      out.write("\t\t},\n");
      out.write("\t\t\n");
      out.write("\t\tloginSectionDisplay : function() {\n");
      out.write("\t\t\tif (this.loginStatus === this.login_Status_Off)\n");
      out.write("\t\t\t\tdocument.getElementById(\"logInLogOut\").innerHTML = \n");
      out.write("\t\t\t\t'<a href = \"/login/form\"> 로그인하기 </a> &nbsp <a href = \"/login/register\"> 회원가입하기 </a>';\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t\tdocument.getElementById(\"logInLogOut\").innerHTML = \n");
      out.write("\t\t\t\t'<a href = \"/login/logout\"> 로그아웃하기 </a>';\n");
      out.write("\t\t},\n");
      out.write("\t\t\n");
      out.write("\t\tloginErrorMessageAlert : function() {\n");
      out.write("\t\t\tif (this.loginErrorMessage)\n");
      out.write("\t\t\t\talert(this.loginErrorMessage);\n");
      out.write("\t\t},\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tvar onloadEvent = {\n");
      out.write("\t\tonloadExecute : function() {\n");
      out.write("\t\t\tloginFeature.loginStatusDisplay();\n");
      out.write("\t\t\tloginFeature.loginSectionDisplay();\n");
      out.write("\t\t\tloginFeature.loginErrorMessageAlert();\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\twindow.onload = onloadEvent.onloadExecute;\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav>\n");
      out.write("\t\t<div id = \"loginStatus\"></div>\n");
      out.write("\t\t<div id = \"logInLogOut\"></div>\n");
      out.write("\t</nav>\n");
      out.write("\t<div class = \"ContentsView\">\n");
      out.write("\t\t<div class = \"userProfileSection\">\n");
      out.write("\t\t\t<div id = \"userProfilePicSection\" \n");
      out.write("\t\t\tstyle = \"background-image: url('/images/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.profileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\">\n");
      out.write("\t\t\t\t<!-- div style contains img src -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id = \"userNickNameSection\">\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id = \"userInfo\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<section class = \"userBoard\">\n");
      out.write("\t\t<div id = \"boardRegisterSection\"></div>\n");
      out.write("\t\t<div class = \"boardScollSection\"></div>\n");
      out.write("\t</section>\n");
      out.write("\t<aside class = \"otherUsers\"></aside>\n");
      out.write("<!-- \t<script src = \"/javascripts/potopotophoto.js\"></script> -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
